# Generated by Django 5.2.17 on 2026-08-07 19:27

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'base_manager_name': 'all_objects', 'ordering': ['name']},
        ),
        migrations.AlterModelManagers(
            name='player',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='is_temporary',
            field=models.BooleanField(default=False, help_text='Convidado criado só para uma partida (lista de nomes colada). Não aparece no cadastro de Jogadores e é removido quando a partida é concluída.'),
        ),
    ]
