# Generated by Django 5.2.17 on 2026-08-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_is_temporary'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='photo_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='players/thumbs/'),
        ),
    ]
