# Generated by Django 5.2.17 on 2026-08-11 01:58

from django.db import migrations, models


def preencher_phone_digits(apps, schema_editor):
    """Normaliza os telefones já cadastrados.

    Sem este passo, o login por telefone só funcionaria para fichas salvas
    **depois** da migration — as 25 que já existem ficariam de fora sem
    nenhum sinal de erro.
    """
    from apps.players.models import normalize_phone

    Player = apps.get_model("players", "Player")
    atualizados = []
    for player in Player.objects.exclude(phone="").only("id", "phone"):
        digits = normalize_phone(player.phone)
        if digits:
            player.phone_digits = digits
            atualizados.append(player)

    if atualizados:
        Player.objects.bulk_update(atualizados, ["phone_digits"], batch_size=500)


def limpar_phone_digits(apps, schema_editor):
    """Reversão: o campo é derivado, então basta esvaziá-lo."""
    Player = apps.get_model("players", "Player")
    Player.objects.update(phone_digits="")


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_player_photo_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='phone_digits',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20),
        ),
        migrations.RunPython(preencher_phone_digits, limpar_phone_digits),
    ]
