# Generated by Django 5.2.17 on 2026-08-05 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_membership_options'),
        ('matches', '0002_periodic_task'),
        ('players', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('algorithm', models.CharField(default='simulated_annealing', max_length=50)),
                ('weights', models.JSONField(blank=True, default=dict)),
                ('score_balance', models.FloatField()),
                ('score_position', models.FloatField()),
                ('score_repetition', models.FloatField()),
                ('total_score', models.FloatField()),
                ('iterations_run', models.PositiveIntegerField()),
                ('is_current', models.BooleanField(default=True)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draws_executed', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draws', to='matches.match')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('order_index', models.PositiveSmallIntegerField(default=0)),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='draws.draw')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='TeamPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('skill_snapshot', models.PositiveSmallIntegerField()),
                ('used_secondary_position', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_players', to='players.player')),
                ('position_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='players.position')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_players', to='draws.team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('team', 'player'), name='unique_team_player')],
            },
        ),
    ]
