# Generated by Django 5.2.17 on 2026-08-06 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draws', '0002_periodic_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('goals_scored', models.PositiveIntegerField(blank=True, null=True)),
                ('goals_conceded', models.PositiveIntegerField(blank=True, null=True)),
                ('result', models.CharField(choices=[('win', 'Vitória'), ('loss', 'Derrota'), ('draw', 'Empate')], max_length=10)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='draws.team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
