# Generated by Django 5.2.17 on 2026-08-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draws', '0004_draw_trigger'),
        ('players', '0002_player_is_temporary'),
    ]

    operations = [
        migrations.AddField(
            model_name='draw',
            name='formation',
            field=models.CharField(blank=True, help_text="Formação padrão escolhida para este sorteio, no formato '2-2-2' (só jogadores de linha; o goleiro não entra na notação). Vazio = sorteio sem formação, em que o campo desenha as linhas pela posição cadastrada de cada jogador.", max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='formation',
            field=models.CharField(blank=True, help_text='Formação **deste** time. Começa igual à do sorteio, mas cada time pode ter a sua — o organizador escolhe por time.', max_length=20),
        ),
        migrations.AddField(
            model_name='teamplayer',
            name='line_index',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Linha da formação (0 = mais defensiva).', null=True),
        ),
        migrations.AddField(
            model_name='teamplayer',
            name='slot_index',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Posição dentro da linha, da esquerda para a direita.', null=True),
        ),
        migrations.AddIndex(
            model_name='teamplayer',
            index=models.Index(fields=['team', 'line_index', 'slot_index'], name='teamplayer_slot_idx'),
        ),
    ]
