# Generated by Django 5.2.17 on 2026-08-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('draw_created', 'Sorteio realizado'), ('player_moved', 'Jogador movido entre times'), ('confirmation_changed', 'Confirmação alterada'), ('waitlist_added', 'Entrou na lista de espera'), ('waitlist_promoted', 'Promovido da lista de espera')], max_length=30),
        ),
    ]
