# Generated by Django 5.2.17 on 2026-08-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('draw_created', 'Sorteio realizado'), ('player_moved', 'Jogador movido entre times'), ('confirmation_changed', 'Confirmação alterada'), ('waitlist_added', 'Entrou na lista de espera'), ('waitlist_promoted', 'Promovido da lista de espera'), ('organization_created', 'Organização criada'), ('organization_updated', 'Organização alterada'), ('membership_changed', 'Perfil de usuário alterado'), ('charge_created', 'Mensalidade lançada'), ('charge_canceled', 'Mensalidade cancelada'), ('payment_registered', 'Baixa de pagamento')], max_length=30),
        ),
    ]
