# Generated by Django 5.2.17 on 2026-08-10 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_superadmin_alter_membership_role'),
        ('audit', '0004_alter_auditlog_action'),
        ('draws', '0004_draw_trigger'),
        ('matches', '0007_goalkeepers_default_zero'),
        ('players', '0002_player_is_temporary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='entity',
            field=models.CharField(blank=True, help_text='Tipo do alvo: charge, payment, player_monthly_fee…', max_length=50),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='entity_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('draw_created', 'Sorteio realizado'), ('player_moved', 'Jogador movido entre times'), ('confirmation_changed', 'Confirmação alterada'), ('waitlist_added', 'Entrou na lista de espera'), ('waitlist_promoted', 'Promovido da lista de espera'), ('match_created', 'Partida criada'), ('match_updated', 'Partida alterada'), ('match_canceled', 'Partida cancelada'), ('organization_created', 'Organização criada'), ('organization_updated', 'Organização alterada'), ('membership_changed', 'Perfil de usuário alterado'), ('charge_created', 'Mensalidade lançada'), ('charge_canceled', 'Mensalidade cancelada'), ('charge_updated', 'Mensalidade alterada'), ('charges_generated', 'Competência gerada'), ('payment_registered', 'Baixa de pagamento'), ('payment_canceled', 'Baixa cancelada'), ('fee_changed', 'Valor da mensalidade alterado'), ('fee_bulk_changed', 'Valor da mensalidade alterado em massa')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['organization', 'entity', 'entity_id'], name='audit_audit_organiz_8407ac_idx'),
        ),
    ]
