# Generated by Django 5.2.17 on 2026-08-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0010_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('draw_created', 'Sorteio realizado'), ('player_moved', 'Jogador movido entre times'), ('player_position_changed', 'Posição do jogador alterada'), ('players_swapped', 'Jogadores trocados entre si'), ('formation_changed', 'Formação do time alterada'), ('confirmation_changed', 'Confirmação alterada'), ('waitlist_added', 'Entrou na lista de espera'), ('waitlist_promoted', 'Promovido da lista de espera'), ('match_created', 'Partida criada'), ('match_updated', 'Partida alterada'), ('match_canceled', 'Partida cancelada'), ('login_generated', 'Login gerado'), ('logins_bulk_generated', 'Logins gerados em massa'), ('password_reset', 'Senha redefinida pelo gestor'), ('password_changed', 'Senha alterada pelo próprio usuário'), ('organization_created', 'Organização criada'), ('organization_updated', 'Organização alterada'), ('membership_changed', 'Perfil de usuário alterado'), ('charge_created', 'Mensalidade lançada'), ('charge_canceled', 'Mensalidade cancelada'), ('charge_updated', 'Mensalidade alterada'), ('charges_generated', 'Competência gerada'), ('payment_registered', 'Baixa de pagamento'), ('payment_canceled', 'Baixa cancelada'), ('fee_changed', 'Valor da mensalidade alterado'), ('fee_bulk_changed', 'Valor da mensalidade alterado em massa'), ('charges_resynced', 'Mensalidades em aberto atualizadas'), ('fee_plan_changed', 'Plano de mensalidade alterado'), ('payment_bulk_registered', 'Baixa em massa'), ('charges_due_date_changed', 'Vencimento alterado em massa'), ('expense_created', 'Despesa lançada'), ('expense_updated', 'Despesa alterada'), ('expense_canceled', 'Despesa cancelada'), ('expenses_generated', 'Custos fixos gerados')], max_length=30),
        ),
    ]
