# Generated by Django 5.2.17 on 2026-08-10 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_superadmin_alter_membership_role'),
        ('finance', '0002_periodic_task'),
        ('players', '0002_player_is_temporary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerMonthlyFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_from', models.CharField(help_text='Competência inicial de vigência, no formato AAAA-MM.', max_length=7)),
                ('reason', models.TextField(blank=True)),
                ('batch', models.UUIDField(blank=True, db_index=True, help_text='Identificador da alteração em massa que criou esta vigência.', null=True)),
            ],
            options={
                'ordering': ['-effective_from', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_cancelled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('registered', 'Registrado'), ('canceled', 'Cancelado')], default='registered', max_length=20),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['organization', 'status', 'paid_at'], name='finance_pay_organiz_a57bdc_idx'),
        ),
        migrations.AddField(
            model_name='playermonthlyfee',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_fees_defined', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playermonthlyfee',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='playermonthlyfee',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_fees', to='players.player'),
        ),
        migrations.AddIndex(
            model_name='playermonthlyfee',
            index=models.Index(fields=['organization', 'player', 'effective_from'], name='finance_pla_organiz_b65b03_idx'),
        ),
        migrations.AddConstraint(
            model_name='playermonthlyfee',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('player', 'effective_from'), name='unique_player_fee_per_reference'),
        ),
    ]
