# Generated by Django 5.2.17 on 2026-08-10 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_superadmin_alter_membership_role'),
        ('finance', '0003_playermonthlyfee_payment_cancellation_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_day', models.PositiveSmallIntegerField(default=10, help_text='Dia do mês em que o custo costuma ser pago.')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.organization')),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('fixed', 'Custo fixo mensal'), ('extra', 'Custo extra')], default='extra', max_length=20)),
                ('description', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(help_text='Competência no formato AAAA-MM.', max_length=7)),
                ('incurred_on', models.DateField(help_text='Data em que a despesa foi paga/realizada.')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('registered', 'Registrada'), ('canceled', 'Cancelada')], default='registered', max_length=20)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_cancelled', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.organization')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_registered', to=settings.AUTH_USER_MODEL)),
                ('recurring', models.ForeignKey(blank=True, help_text='Cadastro de custo fixo que originou esta despesa, quando houver.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='finance.recurringexpense')),
            ],
            options={
                'ordering': ['-reference', '-incurred_on', 'description'],
                'indexes': [models.Index(fields=['organization', 'reference', 'kind'], name='finance_exp_organiz_3395c9_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('recurring__isnull', False)), fields=('recurring', 'reference'), name='unique_fixed_expense_per_reference')],
            },
        ),
    ]
