# Generated by Django 5.2.17 on 2026-08-11 02:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_recurringexpense_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='late_fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='membershipfeeplan',
            name='late_fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Multa fixa por atraso. Zero desativa a cobrança de multa.', max_digits=10),
        ),
    ]
