# Generated by Django 5.2.17 on 2026-08-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_charge_late_fee_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='due_date',
            field=models.DateField(blank=True, help_text='Data de vencimento da despesa, quando houver.', null=True),
        ),
    ]
