# Generated by Django 5.2.17 on 2026-08-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_periodic_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringgame',
            name='max_players_per_team_line',
            field=models.PositiveSmallIntegerField(default=8, help_text='Jogadores de linha (sem contar o goleiro) por time, no máximo.'),
        ),
        migrations.AddField(
            model_name='recurringgame',
            name='min_players_per_team_line',
            field=models.PositiveSmallIntegerField(default=4, help_text='Jogadores de linha (sem contar o goleiro) por time, no mínimo.'),
        ),
        migrations.AlterField(
            model_name='recurringgame',
            name='max_players',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Calculado: teams_count * (max_players_per_team_line + 1 goleiro).'),
        ),
        migrations.AlterField(
            model_name='recurringgame',
            name='min_players',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Calculado: teams_count * (min_players_per_team_line + 1 goleiro).'),
        ),
    ]
