# Generated by Django 5.2.17 on 2026-08-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_recurringgame_max_players_per_team_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='draw_time',
            field=models.TimeField(blank=True, help_text='Horário do sorteio automático desta partida. Quando vazio, herda o horário do jogo recorrente; sem nenhum dos dois, a partida nunca é sorteada automaticamente.', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='match',
            name='name',
            field=models.CharField(blank=True, help_text='Identificação da partida (usado sobretudo em partidas avulsas).', max_length=150),
        ),
        migrations.AddField(
            model_name='match',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recurringgame',
            name='days_before_to_generate',
            field=models.PositiveSmallIntegerField(default=7, help_text='Com quantos dias de antecedência a próxima partida é criada automaticamente. O padrão (7) reproduz o comportamento histórico: como a recorrência é semanal, a partida seguinte era criada assim que a anterior passava.'),
        ),
    ]
