# Generated by Django 5.2.17 on 2026-08-07 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_membership_options'),
        ('matches', '0004_match_manual_fields_and_more'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(default=1)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['position', 'joined_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='confirmation',
            name='unique_confirmation_per_match_player',
        ),
        migrations.AddConstraint(
            model_name='confirmation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('match', 'player'), name='unique_confirmation_per_match_player'),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='matches.match'),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='players.player'),
        ),
        migrations.AddIndex(
            model_name='waitlistentry',
            index=models.Index(fields=['match', 'position'], name='matches_wai_match_i_dae99d_idx'),
        ),
        migrations.AddConstraint(
            model_name='waitlistentry',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('match', 'player'), name='unique_waitlist_per_match_player'),
        ),
    ]
