# Generated by Django 5.2.17 on 2026-08-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_waitlistentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='goalkeepers_per_team',
            field=models.PositiveSmallIntegerField(default=1, help_text='Quantos goleiros cada time reserva nesta partida. Copiado do jogo recorrente quando a partida é gerada por ele. Use 0 quando o goleiro é fixo e não é sorteado.'),
        ),
        migrations.AddField(
            model_name='recurringgame',
            name='goalkeepers_per_team',
            field=models.PositiveSmallIntegerField(default=1, help_text='Quantos goleiros cada time reserva. Use 0 quando o goleiro é fixo e não participa do sorteio — aí a partida conta só jogadores de linha.'),
        ),
        migrations.AlterField(
            model_name='recurringgame',
            name='max_players',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Calculado: teams_count * (max_players_per_team_line + goalkeepers_per_team).'),
        ),
        migrations.AlterField(
            model_name='recurringgame',
            name='min_players',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Calculado: teams_count * (min_players_per_team_line + goalkeepers_per_team).'),
        ),
    ]
