# Generated by Django 5.2.17 on 2026-08-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_match_goalkeepers_per_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='goalkeepers_per_team',
            field=models.PositiveSmallIntegerField(default=0, help_text='Quantos goleiros cada time reserva nesta partida. Copiado do jogo recorrente quando a partida é gerada por ele. Use 0 quando o goleiro é fixo e não é sorteado.'),
        ),
        migrations.AlterField(
            model_name='recurringgame',
            name='goalkeepers_per_team',
            field=models.PositiveSmallIntegerField(default=0, help_text='Quantos goleiros cada time reserva. Use 0 quando o goleiro é fixo e não participa do sorteio — aí a partida conta só jogadores de linha.'),
        ),
    ]
