# Generated by Django 5.2.17 on 2026-08-05 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_plan_organization_membership'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['-created_at']},
        ),
    ]
