# Generated by Django 5.2.17 on 2026-08-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_membership_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_superadmin',
            field=models.BooleanField(default=False, help_text='Super Administrador: administra o sistema inteiro e acessa qualquer organização sem precisar de vínculo. Diferente de `is_superuser`, que é só do Django admin.'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('organizador', 'Gerente'), ('jogador', 'Jogador'), ('visualizador', 'Visualizador')], max_length=20),
        ),
    ]
